### ISSUE TITLE
Internal server error on checkout for some native currencies - need to fix currency exchange provider

### ISSUE THREAD

**Issue by bmann** [vic-en/pretix-eth-payment-plugin#2]
I put in an Ethereum address and after pressing "Continue", get an internal server error.

**Comment by vic-en** [comment]
That must have been a network issue. Try again and let me know if the network persists.

**Comment by bmann** [comment]
Still an issue. I enter address here (see screenshot) and then on Continue get internal server error

![screenshot 2019-02-27 at 11 06 12](https://user-images.githubusercontent.com/280420/53515878-dd536b00-3a7f-11e9-8d4b-e653564ec017.png)

**Comment by bmann** [comment]
From chat, it looks like this is an issue with currency exchange. Re-labeling title.

**Comment by vic-en** [comment]
Other native currencies are now fully supported.
